### ISSUE TITLE
无限超武 是否有可能导致内存泄漏？

### ISSUE THREAD

**Issue by pjy612** [AdjWang/RA2YurisRevengeTrainer#14]
发现 开着无限超武 CPU 占用会高。
有好几次 其他程序提示内存错误 和退出。。。最后导致 死机 和 黑屏。

（我之前以为是 cnc_ddraw 或游戏本身问题，然后我又换了 心灵终结版本玩 中间又提示了一次，理论上CE注入的脚本应该不会有这种问题。 之前我以为是 社会 那个功能引起的。但后面没开 也出现了... ）

我不确定是不是这个功能引起的。
我先不使用那个功能看看效果...
后面会再观望一下... 先 mark 一下

**Comment by pjy612** [comment]
我自己拿C#找了个Memory.dll 仿着实现了下这套逻辑。
估计 加个等待会好一些。
然后就没啥问题了。
心灵终结 超武大概有 137 个。
反正就是 循环的时候 判断下 基址+拿到的偏移还是不是原来的地址。
另外别写那么快好像就没问题。

**Comment by AdjWang** [comment]
谢谢你的实验，很有参考价值。
`+6F` 那数据类型是 byte ，应该只取 0 和 1 ，别的不是这个标识位的数据。
