### ISSUE TITLE
成为幽灵玩家

### ISSUE THREAD

**Issue by dont-beat-up-the-doctor** [AdjWang/RA2YurisRevengeTrainer#17]
成为幽灵玩家后，点击建筑页面，电厂建造呈循环，基于npatch的尤里的复仇MOD，另外一个建议，能否给功能加上全局快捷键，如此无需反复切出游戏，谢谢

**Comment by AdjWang** [comment]
看不懂"电厂建造呈循环"这个现象，可以描述细致些吗？

**Comment by dont-beat-up-the-doctor** [comment]
Sorry，可能是我表述的不够清楚，一开局启用幽灵模式＋快速建造，非极速建造，电厂建造迅速完成，但是不能点击释放，再次点击电厂建造，则重复上移过程，因此游戏不能继续下去，我使用的是基于NPatch的一个mod，原隐风之龙mod的作者之一，mod中无新元素素材添加，感谢回复



发自我的小米手机
在 AdjWang ***@***.***>，2023年11月27日 下午4:48写道：

看不懂"电厂建造呈循环"这个现象，可以描述细致些吗？

**Comment by AdjWang** [comment]
无论如何，感谢使用和报告。那个功能其实挺鸡肋，下个版本应该会删掉。快捷键的事之前也有人提过，确实应该加，只是我最近挺忙，估计得再过几个月。
