### ISSUE TITLE
【建议】区分单机作弊和联网对战辅助

### ISSUE THREAD

**Issue by bigsinger** [AdjWang/RA2YurisRevengeTrainer#21]
单机自己玩可以使用任何变态的功能，例如修改三星，更换归属，无敌等等。
但是如果联网对战，建议不使用这些变态功能，会影响游戏的可玩性和平衡性，建议做个区分。

建议在联网的时候，工具只提供一些简单的、辅助性的、解放双手的功能，例如：

1. 开个全图或雷达
2. 自动删除信标
3. 自动检箱子
4. ……

**Comment by AdjWang** [comment]
我觉得这些功能里，只有自动删除信标不影响公平性。有关联网客户端辅助开发的困难在 issue #19 里解释过了，这里不重复了。

**Comment by bigsinger** [comment]
> 我觉得这些功能里，只有自动删除信标不影响公平性。有关联网客户端辅助开发的困难在 issue #19 里解释过了，这里不重复了。

全图功能对新手友好一些，对老手影响不大，对游戏损害不大。
全图功能我测试了，可以联网使用。

**Comment by AdjWang** [comment]
换一种说法，如果对战的玩家有个选项，选择是否允许对方开全图而自己不行，我觉得玩家不会愿意的……

**Comment by bigsinger** [comment]
> 换一种说法，如果对战的玩家有个选项，选择是否允许对方开全图而自己不行，我觉得玩家不会愿意的……维护老玩家的权益也很重要。

这个我跟群里的老玩家交流过这个，他们不care的 意思是我开全图一样打不过他们哈哈

**Comment by AdjWang** [comment]
都是傲慢之罪，让 08 来杀杀他们的锐气(╯‵□′)╯︵┻━┻。综合考虑我还是拒绝这个功能。

**Comment by bigsinger** [comment]
> 都是傲慢之罪，让 08 来杀杀他们的锐气(╯‵□′)╯︵┻━┻。综合考虑我还是拒绝这个功能。

我一开始跟你想的一样。结果：08 月亮3 威龙 等都不是他的对手，你想要结识吗  我有他们群 可以拉你进去一起玩。

**Comment by bigsinger** [comment]
> 都是傲慢之罪，让 08 来杀杀他们的锐气(╯‵□′)╯︵┻━┻。综合考虑我还是拒绝这个功能。

没事全图的我已经做好了。  现在就差自动删除信标的，我觉得信标这个是真麻烦，如果能自动删除 会非常方便。

**Comment by AdjWang** [comment]
信标的事我可以去看看，不过得再过几个月，最近比较忙……后面的事就跟进 issue #19 吧。

**Comment by bigsinger** [comment]
没问题 不急
