### ISSUE TITLE
作者您好，请帮帮我，我是一个小白

### ISSUE THREAD

**Issue by Cby000** [AdjWang/RA2YurisRevengeTrainer#22]
以下是我运行到最后一步遇到的问题，麻烦你教教我怎样解决

D:\Git\RA2YurisRevengeTrainer>set NUMBER_OF_PROCESSORS
NUMBER_OF_PROCESSORS=16

D:\Git\RA2YurisRevengeTrainer>cmake --build ./build --config Release --target ra2_trainer -j %NUMBER_OF_PROCESSORS%
适用于 .NET Framework MSBuild 版本 17.11.2+c078802d4

  正在扫描源以查找模块依赖项...
  autoassembler.cpp
  正在扫描源以查找模块依赖项...
  glfw.vcxproj -> D:\Git\RA2YurisRevengeTrainer\build\deps\glfw\src\Release\glfw3.lib
  fmt.vcxproj -> D:\Git\RA2YurisRevengeTrainer\build\deps\fmt\Release\fmt.lib
  libimgui.vcxproj -> D:\Git\RA2YurisRevengeTrainer\build\Release\libimgui.lib
D:\Git\RA2YurisRevengeTrainer\src\aa_engine\autoassembler.cpp(1336,1): error C1057: 宏扩展中遇到意外的文件结束 [D:\Git\RA2YurisReven
geTrainer\build\src\aa_engine\aa_engine.vcxproj]
D:\Git\RA2YurisRevengeTrainer\src\aa_engine\autoassembler.cpp(1336,1): fatal error C1057: 宏扩展中遇到意外的文件结束 [D:\Git\RA2Yuri
sRevengeTrainer\build\src\aa_engine\aa_engine.vcxproj]
D:\Visual Studio\Program Files\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(503,5): warning MSB80
74: 无法读取模块依赖项文件 aa_engine.dir\Release\autoassembler.cpp.module.json: 应为来自命名空间“”的元素“root”。。遇到名称为“”、命名空间为“”的“None”。 生成顺序可
能不正确。 [D:\Git\RA2YurisRevengeTrainer\build\src\aa_engine\aa_engine.vcxproj]
  正在编译...
  autoassembler.cpp
D:\Git\RA2YurisRevengeTrainer\src\aa_engine\autoassembler.cpp(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Un
icode 格式以防止数据丢失 [D:\Git\RA2YurisRevengeTrainer\build\src\aa_engine\aa_engine.vcxproj]
D:\Git\RA2YurisRevengeTrainer\src\aa_engine\autoassembler.cpp(1201,1): warning C4819: 该文件包含不能在当前代码页(936)中 表示的字符。请将该文件保存为
 Unicode 格式以防止数据丢失 [D:\Git\RA2YurisRevengeTrainer\build\src\aa_engine\aa_engine.vcxproj]
D:\Git\RA2YurisRevengeTrainer\src\aa_engine\autoassembler.cpp(1336,19): error C2001: 常量中有换行符 [D:\Git\RA2YurisRevengeTra
iner\build\src\aa_engine\aa_engine.vcxproj]
D:\Git\RA2YurisRevengeTrainer\src\aa_engine\autoassembler.cpp(2298,1): warning C4819: 该文件包含不能在当前代码页(936)中 表示的字符。请将该文件保存为
 Unicode 格式以防止数据丢失 [D:\Git\RA2YurisRevengeTrainer\build\src\aa_engine\aa_engine.vcxproj]
D:\Git\RA2YurisRevengeTrainer\src\aa_engine\autoassembler.cpp(1336,1): error C1057: 宏扩展中遇到意外的文件结束 [D:\Git\RA2YurisReven
geTrainer\build\src\aa_engine\aa_engine.vcxproj]

**Comment by AdjWang** [comment]
https://github.com/AdjWang/RA2YurisRevengeTrainer/blob/4f39fb0377d61ea774e2a90125626487b8129181/CMakeLists.txt#L10
改成 `add_compile_options(/MP /Gy /GS- /utf-8)` 试试

**Comment by Cby000** [comment]
感谢，完美解决编译成功！

**Comment by Cby000** [comment]
ok



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月23日(星期五) 上午9:13
收件人: ***@***.***&gt;; 
抄送: "Green ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AdjWang/RA2YurisRevengeTrainer] 作者您好，请帮帮我，我是一个小白 (Issue #22)














 
Closed #22 as completed.
