### ISSUE TITLE
出现寻址问题

### ISSUE THREAD

**Issue by majwyk** [AdjWang/RA2YurisRevengeTrainer#3]
没有重新编译，就拿`Release`文件夹下的`RATrainer.exe`试了一下，部分功能可以用，部分功能会有寻址问题，提示地址无效。

> The address specifier is not valid: "gamemd.exe"+XXXXX:

点地图全开会弹出一个`true`
试了一下，框选区的功能除了**任务调速**我没测试，其他的几十个只有**无限超武**和**永久雷达**是正常工作，**禁止建造选项自动刷新**没有弹出地址无效的警告，但是进了游戏看发现并没有生效，剩下的都会弹出地址无效并且在游戏中不生效。
我的版本是从红警之家下的尤里的复仇v1.001，不知道作者放在`Release`文件夹下的程序是用`Debug`编译的还是游戏程序的问题。

**Comment by AdjWang** [comment]
请确认一定要用管理员身份启动 RATrainer.exe 
我下了一个 `http://www.uc129.com/xiazai/ra2/6615.html` 没问题，能发我下你的下载链接吗？或者把你的 gamemd.exe 邮件给我。wlstemp@163.com

**Comment by majwyk** [comment]
您好，我是王一康。邮件已收到，我会尽快回复！
