### ISSUE TITLE
【参考】开启红警游戏的调试日志，有助于分析

### ISSUE THREAD

**Issue by bigsinger** [AdjWang/RA2YurisRevengeTrainer#33]
源码在这里：
[红警2共和国之辉开启调试功能（干货）](https://www.52pojie.cn/thread-961927-1-1.html)

希望对作者有用。

**Comment by AdjWang** [comment]
谢谢，已经接入调试。尤里的复仇1.001日志打印函数虚拟地址在 `0x004068E0`
